// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtV9KvnKNdpUgXCbxJv-g-fgv-J6oyZbY',
    appId: '1:1073634890771:web:5d1ef6fbe4e444f2b89be6',
    messagingSenderId: '1073634890771',
    projectId: 'm2dfschatapp',
    authDomain: 'm2dfschatapp.firebaseapp.com',
    storageBucket: 'm2dfschatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEmR7qBBp3HAAJFw7qhiPZt2UAX4oHoMg',
    appId: '1:1073634890771:android:ff4af01cf9676324b89be6',
    messagingSenderId: '1073634890771',
    projectId: 'm2dfschatapp',
    storageBucket: 'm2dfschatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpcrDqSpYbwXbASvZglmZ3I3XXCu5OQ84',
    appId: '1:1073634890771:ios:484e722b8e081fefb89be6',
    messagingSenderId: '1073634890771',
    projectId: 'm2dfschatapp',
    storageBucket: 'm2dfschatapp.appspot.com',
    iosBundleId: 'com.example.m2dfsChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpcrDqSpYbwXbASvZglmZ3I3XXCu5OQ84',
    appId: '1:1073634890771:ios:85dd988ad88dfdceb89be6',
    messagingSenderId: '1073634890771',
    projectId: 'm2dfschatapp',
    storageBucket: 'm2dfschatapp.appspot.com',
    iosBundleId: 'com.example.m2dfsChatApp.RunnerTests',
  );
}
